title: Gyungmin's Home
logo: /assets/img/gyungmin.jpg
description: 조경민 (Gyungmin Jo) <br/>
  국가유산진흥원 근무 <br/>
  Working at the Korea Heritage Agency <br/>
  한국학중앙연구원 박사과정 <br/>
  Ph.D. Student at the Academy of Korean Studies <br/>
  email: jo.gyungmin@gmail.com <br/>
show_downloads: false
#google_analytics:
#theme: jekyll-theme-minimal