title: Gyungmin's Home
logo: /assets/img/gyungmin.jpg
description: 조경민 (Gyungmin Jo) <br/>
  Working at the Korea Heritage Foundation <br/>
  Ph.D. Student at the Academy of Korean Studies <br/>
  email_ jo.gyungmin@gmail.com
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal