title: Gyungmin's Home
logo: /assets/img/gyungmin.jpg
description: 조경민(曺京敏), Gyungmin Jo 
  Ph.D. Student in Academy of Korean Studies
email: jo.gyungmin@gmail.com
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
